-- 1. Create Users Table (Skips if already exists)
CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    registration_number TEXT,
    is_kiu_student BOOLEAN DEFAULT FALSE
);

-- 2. Create Learning Materials Table
CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    course_program TEXT NOT NULL,
    course_name TEXT NOT NULL,
    week INTEGER DEFAULT 1,
    video_url TEXT,
    notes_url TEXT,
    image_url TEXT
);

-- 3. Create Portal Settings Table
CREATE TABLE IF NOT EXISTS portal_settings (
    id INTEGER PRIMARY KEY,
    login_bg_url TEXT NOT NULL
);

-- 4. Safe Insert for Default Settings
-- This only inserts the background if ID 1 doesn't exist yet
INSERT INTO portal_settings (id, login_bg_url)
VALUES (1, 'https://images.unsplash.com/photo-1497366216548-37526070297c')
ON CONFLICT (id) DO NOTHING;
